###################################################################

# Created by write_sdc on Mon Jun  1 22:32:18 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max WCCOM -max_library                               \
fsa0m_a_generic_core_ss1p62v125c\
                         -min BCCOM -min_library                               \
fsa0m_a_generic_core_ff1p98vm40c
set_wire_load_model -name G200K -library fsa0m_a_generic_core_tt1p8v25c
set_max_fanout 6 [current_design]
set_max_area 0
set_load -pin_load 10 [get_ports o_valid]
set_load -pin_load 10 [get_ports {o_theta[0]}]
set_load -pin_load 10 [get_ports {o_theta[-1]}]
set_load -pin_load 10 [get_ports {o_theta[-2]}]
set_load -pin_load 10 [get_ports {o_theta[-3]}]
set_load -pin_load 10 [get_ports {o_theta[-4]}]
set_load -pin_load 10 [get_ports {o_theta[-5]}]
set_load -pin_load 10 [get_ports {o_theta[-6]}]
set_load -pin_load 10 [get_ports {o_theta[-7]}]
set_load -pin_load 10 [get_ports {channel[1]}]
set_load -pin_load 10 [get_ports {channel[0]}]
set_load -pin_load 10 [get_ports {o_x[5]}]
set_load -pin_load 10 [get_ports {o_x[4]}]
set_load -pin_load 10 [get_ports {o_x[3]}]
set_load -pin_load 10 [get_ports {o_x[2]}]
set_load -pin_load 10 [get_ports {o_x[1]}]
set_load -pin_load 10 [get_ports {o_x[0]}]
set_load -pin_load 10 [get_ports {o_x[-1]}]
set_load -pin_load 10 [get_ports {o_x[-2]}]
set_load -pin_load 10 [get_ports {o_x[-3]}]
set_load -pin_load 10 [get_ports {o_x[-4]}]
set_load -pin_load 10 [get_ports {o_y[5]}]
set_load -pin_load 10 [get_ports {o_y[4]}]
set_load -pin_load 10 [get_ports {o_y[3]}]
set_load -pin_load 10 [get_ports {o_y[2]}]
set_load -pin_load 10 [get_ports {o_y[1]}]
set_load -pin_load 10 [get_ports {o_y[0]}]
set_load -pin_load 10 [get_ports {o_y[-1]}]
set_load -pin_load 10 [get_ports {o_y[-2]}]
set_load -pin_load 10 [get_ports {o_y[-3]}]
set_load -pin_load 10 [get_ports {o_y[-4]}]
create_clock [get_ports clk]  -period 5  -waveform {0 2.5}
set_clock_latency 0.5  [get_clocks clk]
set_clock_uncertainty 0.1  [get_clocks clk]
set_input_delay -clock clk  -max 1  [get_ports clk]
set_input_delay -clock clk  -max 1  [get_ports rst_n]
set_input_delay -clock clk  -max 1  [get_ports i_valid]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-6]}]
set_input_delay -clock clk  -max 1  [get_ports {i_theta[-7]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x1[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y1[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x2[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y2[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x3[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y3[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_x4[-4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[5]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[4]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[0]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[-1]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[-2]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[-3]}]
set_input_delay -clock clk  -max 1  [get_ports {i_y4[-4]}]
set_output_delay -clock clk  -min 0.5  [get_ports o_valid]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-6]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_theta[-7]}]
set_output_delay -clock clk  -min 0.5  [get_ports {channel[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {channel[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[-1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[-2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[-3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_x[-4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[5]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[4]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[0]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[-1]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[-2]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[-3]}]
set_output_delay -clock clk  -min 0.5  [get_ports {o_y[-4]}]
set_drive 1  [get_ports clk]
set_drive 1  [get_ports rst_n]
set_drive 1  [get_ports i_valid]
set_drive 1  [get_ports {i_theta[0]}]
set_drive 1  [get_ports {i_theta[-1]}]
set_drive 1  [get_ports {i_theta[-2]}]
set_drive 1  [get_ports {i_theta[-3]}]
set_drive 1  [get_ports {i_theta[-4]}]
set_drive 1  [get_ports {i_theta[-5]}]
set_drive 1  [get_ports {i_theta[-6]}]
set_drive 1  [get_ports {i_theta[-7]}]
set_drive 1  [get_ports {i_x1[5]}]
set_drive 1  [get_ports {i_x1[4]}]
set_drive 1  [get_ports {i_x1[3]}]
set_drive 1  [get_ports {i_x1[2]}]
set_drive 1  [get_ports {i_x1[1]}]
set_drive 1  [get_ports {i_x1[0]}]
set_drive 1  [get_ports {i_x1[-1]}]
set_drive 1  [get_ports {i_x1[-2]}]
set_drive 1  [get_ports {i_x1[-3]}]
set_drive 1  [get_ports {i_x1[-4]}]
set_drive 1  [get_ports {i_y1[5]}]
set_drive 1  [get_ports {i_y1[4]}]
set_drive 1  [get_ports {i_y1[3]}]
set_drive 1  [get_ports {i_y1[2]}]
set_drive 1  [get_ports {i_y1[1]}]
set_drive 1  [get_ports {i_y1[0]}]
set_drive 1  [get_ports {i_y1[-1]}]
set_drive 1  [get_ports {i_y1[-2]}]
set_drive 1  [get_ports {i_y1[-3]}]
set_drive 1  [get_ports {i_y1[-4]}]
set_drive 1  [get_ports {i_x2[5]}]
set_drive 1  [get_ports {i_x2[4]}]
set_drive 1  [get_ports {i_x2[3]}]
set_drive 1  [get_ports {i_x2[2]}]
set_drive 1  [get_ports {i_x2[1]}]
set_drive 1  [get_ports {i_x2[0]}]
set_drive 1  [get_ports {i_x2[-1]}]
set_drive 1  [get_ports {i_x2[-2]}]
set_drive 1  [get_ports {i_x2[-3]}]
set_drive 1  [get_ports {i_x2[-4]}]
set_drive 1  [get_ports {i_y2[5]}]
set_drive 1  [get_ports {i_y2[4]}]
set_drive 1  [get_ports {i_y2[3]}]
set_drive 1  [get_ports {i_y2[2]}]
set_drive 1  [get_ports {i_y2[1]}]
set_drive 1  [get_ports {i_y2[0]}]
set_drive 1  [get_ports {i_y2[-1]}]
set_drive 1  [get_ports {i_y2[-2]}]
set_drive 1  [get_ports {i_y2[-3]}]
set_drive 1  [get_ports {i_y2[-4]}]
set_drive 1  [get_ports {i_x3[5]}]
set_drive 1  [get_ports {i_x3[4]}]
set_drive 1  [get_ports {i_x3[3]}]
set_drive 1  [get_ports {i_x3[2]}]
set_drive 1  [get_ports {i_x3[1]}]
set_drive 1  [get_ports {i_x3[0]}]
set_drive 1  [get_ports {i_x3[-1]}]
set_drive 1  [get_ports {i_x3[-2]}]
set_drive 1  [get_ports {i_x3[-3]}]
set_drive 1  [get_ports {i_x3[-4]}]
set_drive 1  [get_ports {i_y3[5]}]
set_drive 1  [get_ports {i_y3[4]}]
set_drive 1  [get_ports {i_y3[3]}]
set_drive 1  [get_ports {i_y3[2]}]
set_drive 1  [get_ports {i_y3[1]}]
set_drive 1  [get_ports {i_y3[0]}]
set_drive 1  [get_ports {i_y3[-1]}]
set_drive 1  [get_ports {i_y3[-2]}]
set_drive 1  [get_ports {i_y3[-3]}]
set_drive 1  [get_ports {i_y3[-4]}]
set_drive 1  [get_ports {i_x4[5]}]
set_drive 1  [get_ports {i_x4[4]}]
set_drive 1  [get_ports {i_x4[3]}]
set_drive 1  [get_ports {i_x4[2]}]
set_drive 1  [get_ports {i_x4[1]}]
set_drive 1  [get_ports {i_x4[0]}]
set_drive 1  [get_ports {i_x4[-1]}]
set_drive 1  [get_ports {i_x4[-2]}]
set_drive 1  [get_ports {i_x4[-3]}]
set_drive 1  [get_ports {i_x4[-4]}]
set_drive 1  [get_ports {i_y4[5]}]
set_drive 1  [get_ports {i_y4[4]}]
set_drive 1  [get_ports {i_y4[3]}]
set_drive 1  [get_ports {i_y4[2]}]
set_drive 1  [get_ports {i_y4[1]}]
set_drive 1  [get_ports {i_y4[0]}]
set_drive 1  [get_ports {i_y4[-1]}]
set_drive 1  [get_ports {i_y4[-2]}]
set_drive 1  [get_ports {i_y4[-3]}]
set_drive 1  [get_ports {i_y4[-4]}]
