%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [E,degrees] = search_with_mono_wrapper_fixpt(x1_q,x1_i,x2_q,x2_i,x3_q,x3_i,x4_q,x4_i,step)
    fm = get_fimath();
    x1_q_in = fi( x1_q, 1, 10, 7, fm );
    x1_i_in = fi( x1_i, 0, 10, 7, fm );
    x2_q_in = fi( x2_q, 1, 10, 6, fm );
    x2_i_in = fi( x2_i, 1, 10, 7, fm );
    x3_q_in = fi( x3_q, 1, 10, 6, fm );
    x3_i_in = fi( x3_i, 1, 10, 6, fm );
    x4_q_in = fi( x4_q, 1, 10, 6, fm );
    x4_i_in = fi( x4_i, 1, 10, 6, fm );
    step_in = fi( step, 0, 2, 0, fm );
    [E_out,degrees_out] = search_with_mono_fixpt( x1_q_in, x1_i_in, x2_q_in, x2_i_in, x3_q_in, x3_i_in, x4_q_in, x4_i_in, step_in );
    E = double( E_out );
    degrees = double( degrees_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Saturate',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
