%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [E, degrees] = search_with_mono_fixpt(x1_q, x1_i, x2_q, x2_i, x3_q, x3_i, x4_q, x4_i, step)
    % Inputs:
    %   x1_q, x1_i, ..., x4_q, x4_i: Real and imaginary parts of the received signals for 4 channels (each should be a vector of length num_iterations + scan_points)
    %   step: Scan resolution in degrees for the initial search phase
    % Outputs:
    %   E: Energy values for each scanned angle during the initial search phase
    %   degrees: The degrees detected through the monopulse search phase

    %% 1. System & Environment Parameters Setup
    % --- Search Parameters ---
    fm = get_fimath();

    scan_start = fi(-60, 1, 7, 0, fm);       % Start angle of scan
    scan_end = fi(60, 0, 6, 0, fm);          % End angle of scan
    scan_step = fi(step, 0, 2, 0, fm);          % Scan resolution (step size in degrees)
    scan_angles = fi(scan_start:scan_step:scan_end, 1, 7, 0, fm);
    num_scan_points = fi(length(scan_angles), 0, 6, 0, fm);
    N = fi(4, 0, 3, 0, fm);                  % Number of antenna elements

    % --- Tracking Parameters ---
    cordic_iter = fi(10, 0, 4, 0, fm);    % Number of iterations for the cordic algorithm

    %% 2. Signal Setup
    X = fi([fi(x1_q + fi(1j, 0, 1, 0, fm)*x1_i, 1, 10, 6, fm); x2_q + fi(1j, 0, 1, 0, fm)*x2_i; x3_q + fi(1j, 0, 1, 0, fm)*x3_i; x4_q + fi(1j, 0, 1, 0, fm)*x4_i], 1, 10, 6, fm);

    %% 2. Hardware Algo: Sequential Scanning & Energy Estimation
    % Initialize array to store calculated energy for each scanned angle

    scan_energy = fi(zeros(1, fi_toint(num_scan_points)), 0, 10, 6, fm);
    max_degree = fi(0, 1, 7, 0, fm);
    max_energy = fi(0, 0, 10, 6, fm);

    % Sweep through all angles
    for i = fi(1, 0, 1, 0, fm):num_scan_points
        current_angle = fi(scan_angles(i), 1, 7, 0, fm);

        SUM_Q = fi(0, 1, 10, 5, fm);
        SUM_I = fi(0, 1, 10, 5, fm);

        for k = fi(1, 0, 1, 0, fm):N
            % Calculate phase: phi = 2*pi * d/L * (k-1) * (theta)
            % phi = 2 * pi * 0.5 * (k-1) * sind(current_angle);
            phi = fi(fi(fi(2 * pi * 0.5, 0, 10, 8, fm) * (k-fi(1, 0, 1, 0, fm)), 'SumMode', 'KeepLSB') * fi(sind_lut_s1(current_angle), 'SumMode', 'KeepLSB'), 1, 10, 5, fm);

            % CORDIC Rotation (Implemented as a function for clarity)
            [fmo_1, fmo_2, ~] = cordic_s1(fi(real(X(k, i)), 1, 10, 3, fm), fi(imag(X(k, i)), 1, 10, 3, fm), phi, fi(10, 0, 4, 0, fm), fi(0, 0, 1, 0, fm));
            Q_rot = fi(fmo_1, 1, 10, 7, fm);
            I_rot = fi(fmo_2, 1, 10, 7, fm); % mode=0 for rotation

            SUM_I(:) = SUM_I + I_rot;
            SUM_Q(:) = SUM_Q + Q_rot;
        end

        % Energy Estimation (Accumulate energy over the sample window)
        energy_approx = fi(sum(abs(SUM_I) + abs(SUM_Q)), 0, 10, 6, fm); 
        % energy_approx = sum(sqrt(SUM_I.^2 + SUM_Q.^2));

        % Store the energy for this angle
        scan_energy(i) = fi(energy_approx, 0, 10, 6, fm);
        if energy_approx > max_energy
            max_degree(:) = current_angle;
            max_energy(:) = energy_approx;
        end
    end

    %% 3. Peak Detection
    % Find the maximum energy and its corresponding angle
    E = fi(scan_energy, 0, 10, 6, fm);

    %% 4. Tracking with Monopulse
    X_track = fi(X(:, num_scan_points+fi(1, 0, 1, 0, fm):fi(end, 0, 9, 0, fm)), 1, 10, 6, fm); % Use the remaining samples for tracking
    theta_track = fi(monopulse_tracking(X_track, N, fi(0.5, 0, 10, 10, fm), cordic_iter, max_degree, fi(2^(-4) * (180/pi), 0, 10, 8, fm)), 1, 8, 0, fm);
    degrees = fi(theta_track, 1, 8, 0, fm);
end

function value = sind_lut_s1(theta)
    % Lookup table for sine values from -60 to 60 degrees with a step of 2 degrees
    % lut = [-0.8660, -0.8480, -0.8290, -0.8090, -0.7880, -0.7660, -0.7431, -0.7193, -0.6947, -0.6691, -0.6428, -0.6157, -0.5878, -0.5592, -0.5299, -0.5000, -0.4695, -0.4384, -0.4067, -0.3746, -0.3420, -0.3090, -0.2756, -0.2419, -0.2079, -0.1736, -0.1392, -0.1045, -0.0698, -0.0349, 0, 0.0349, 0.0698,0.1045, 0.1392, 0.1736, 0.2079, 0.2419, 0.2756, 0.3090, 0.3420, 0.3746, 0.4067, 0.4384,0.4695, 0.5000, 0.5299, 0.5592, 0.5878, 0.6157, 0.6428, 0.6691, 0.6947, 0.7193, 0.7431, 0.7660, 0.7880, 0.8090, 0.8290, 0.8480, 0.8660];
    fm = get_fimath();

    lut = fi([-0.8660, -0.8572, -0.8480, -0.8387, -0.8290, -0.8192, -0.8090, -0.7986, -0.7880, -0.7771, -0.7660, -0.7547, -0.7431, -0.7314, -0.7193, -0.7071, -0.6947, -0.6820, -0.6691, -0.6561, -0.6428, -0.6293, -0.6157, -0.6018, -0.5878, -0.5736, -0.5592, -0.5446, -0.5299, -0.5150, -0.5000, -0.4848, -0.4695, -0.4540, -0.4384, -0.4226, -0.4067, -0.3907, -0.3746, -0.3584, -0.3420, -0.3256, -0.3090, -0.2924, -0.2756, -0.2588, -0.2419, -0.2250, -0.2079, -0.1908, -0.1736, -0.1564, -0.1392, -0.1219, -0.1045, -0.0872, -0.0698, -0.0523, -0.0349, -0.0175, 0.0000, 0.0175, 0.0349, 0.0523, 0.0698, 0.0872, 0.1045, 0.1219, 0.1392, 0.1564, 0.1736, 0.1908, 0.2079, 0.2250, 0.2419, 0.2588, 0.2756, 0.2924, 0.3090, 0.3256, 0.3420, 0.3584, 0.3746, 0.3907, 0.4067, 0.4226, 0.4384, 0.4540, 0.4695, 0.4848, 0.5000, 0.5150, 0.5299, 0.5446, 0.5592, 0.5736, 0.5878, 0.6018, 0.6157, 0.6293, 0.6428, 0.6561, 0.6691, 0.6820, 0.6947, 0.7071, 0.7193, 0.7314, 0.7431, 0.7547, 0.7660, 0.7771, 0.7880, 0.7986, 0.8090, 0.8192, 0.8290, 0.8387, 0.8480, 0.8572, 0.8660], 1, 10, 9, fm);
    
    % Define the range of angles in the lookup table
    angles = fi(-60:1:60, 1, 7, 0, fm);

    % Find the index of the input angle in the lookup table
    index = fi(find(angles == theta, 1), 0, 7, 0, fm);

    % Return the corresponding value or 0 if the angle is not in the table
    if ~isempty(index)
        value = fi(lut(index), 1, 10, 9, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        value = fi(0, 1, 10, 9, fm);
        %F2F: End block
    end
end

function [out_x, out_y, out_z] = cordic_s1(x_in, y_in, z_in, num_iterations, mode)
    % Unified CORDIC algorithm for both Rotation and Vectoring modes
    % Inputs:
    %   x_in, y_in : Input vector coordinates (Real and Imaginary)
    %   z_in       : Target angle (Rotation) or Initial angle offset (Vectoring)
    %   num_iterations : Number of iterations for the CORDIC algorithm (accuracy vs. complexity)
    %   mode       : 0: rotation mode or 1: vector mode
    % Outputs:
    %   out_x, out_y : Output vector coordinates (Real and Imaginary)


    % Precompute arctan values for the iterations
    % atan_table = atan(2.^-(0:num_iterations-1));
    fm = get_fimath();

    atan_table = fi([0.7854  0.4636  0.2450  0.1244  0.0624  0.0312  0.0156  0.0078  0.0039  0.0020  0.0018  0.0005 ], 0, 12, 12, fm);

    x_reg = fi(x_in, 1, 12, 3, fm);
    y_reg = fi(y_in, 1, 12, 3, fm);
    z_reg = fi(z_in, 1, 12, 7, fm);
    
    %% --- ROTATION MODE (Steering the Antenna Phase) ---
    if mode == fi(0, 0, 1, 0, fm)
        % 1. Quadrant Mapping: Fold the angle into [-pi/2, pi/2]
        z_reg = fi(fi_signed(mod(z_reg + fi(pi, 0, 10, 8, fm), fi(2*pi, 0, 10, 7, fm))) - fi(pi, 0, 10, 8, fm), 1, 12, 7, fm); % Wrap to [-pi, pi]
        if z_reg > fi(pi/2, 0, 10, 9, fm)
            x_reg(:) = fi_uminus(x_in); y_reg(:) = fi_uminus(y_in); z_reg = fi(z_reg - fi(pi, 0, 10, 8, fm), 1, 12, 7, fm);
        elseif z_reg < fi(-pi/2, 1, 10, 8, fm)
            x_reg(:) = fi_uminus(x_in); y_reg(:) = fi_uminus(y_in); z_reg = fi(z_reg + fi(pi, 0, 10, 8, fm), 1, 12, 7, fm);
        end
        
        % 2. Iterative Rotation
        for i = fi(0, 0, 1, 0, fm):fi_signed(num_iterations)-fi(1, 0, 1, 0, fm)
            if z_reg > fi(0, 0, 1, 0, fm)
                % Rotate counter-clockwise
                x_temp = fi(x_reg - bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg - (y_reg * 2^(-i))
                y_temp = fi(y_reg + bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg + (
                z_temp = fi(z_reg - atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            else
                % Rotate clockwise
                x_temp = fi(x_reg + bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg + (y_reg * 2^(-i))
                y_temp = fi(y_reg - bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg - (x_reg * 2^(-i))
                z_temp = fi(z_reg + atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            end
            x_reg(:) = x_temp; y_reg(:) = y_temp; z_reg = fi(z_temp, 1, 12, 7, fm);
        end
        
    %% --- VECTORING MODE (Extracting the Phase) ---
    elseif mode == fi(1, 0, 1, 0, fm)
        % 1. Quadrant Mapping: Force the vector into the right half-plane (X > 0)
        if x_reg < fi(0, 0, 1, 0, fm)
            if y_reg >= fi(0, 0, 1, 0, fm)
                z_reg = fi(z_reg + fi(pi, 0, 10, 8, fm), 1, 12, 7, fm); % Vector was in Q2
            else
                z_reg = fi(z_reg - fi(pi, 0, 10, 8, fm), 1, 12, 7, fm); % Vector was in Q3
            end
            x_reg(:) = fi_uminus(x_reg); 
            y_reg(:) = fi_uminus(y_reg);
        end
        
        % 2. Iterative Vectoring (Drive Y to 0)
        for i = fi(0, 0, 1, 0, fm):fi_signed(num_iterations)-fi(1, 0, 1, 0, fm)
            if y_reg > fi(0, 0, 1, 0, fm)
                % Rotate clockwise to reduce Y
                x_temp = fi(x_reg + bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg + (y_reg * 2^(-i))
                y_temp = fi(y_reg - bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg - (x_reg * 2^(-i))
                z_temp = fi(z_reg + atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            else
                % Rotate counter-clockwise to increase Y
                x_temp = fi(x_reg - bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg - (y_reg * 2^(-i))
                y_temp = fi(y_reg + bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg + (x_reg * 2^(-i))
                z_temp = fi(z_reg - atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            end
            x_reg(:) = x_temp; y_reg(:) = y_temp; z_reg = fi(z_temp, 1, 12, 7, fm);
        end
    end
    
    % --- Apply CORDIC Gain (approx 1.6467 for 10 iters) ---
    % In a strict 3000 FF hardware design, you might skip this division 
    % if you only care about the phase (z_reg) or relative magnitude.
    % gain = prod(sqrt(1 + 2.^-(2*(0:num_iterations-1))));
    gain = fi(1.6467, 0, 10, 9, fm); % Precomputed gain for 10 iterations
    out_x = fi(fi_div(x_reg, gain), 1, 10, 2, fm);
    out_y = fi(fi_div(y_reg, gain), 1, 10, 2, fm);
    out_z = fi(z_reg, 1, 10, 7, fm);
end

% =========================================================================
% Function: monopulse_tracking
% Multiplier-less monopulse tracking using CORDIC for rotation and vectoring.
% The received-signal matrix X (N x num_samples) must be provided by the caller.
% Usage:
%   theta_track = monopulse_tracking(X, N, d_lambda, cordic_iters, theta_init, K_track)
function theta_track = monopulse_tracking(X, N_1, d_lambda_1, cordic_iters_1, theta_init_1, K_track_1)

% Validate input X
fm = get_fimath();
K_track = fi(K_track_1, 0, 10, 8, fm);
N = fi(N_1, 0, 3, 0, fm);
cordic_iters = fi(cordic_iters_1, 0, 4, 0, fm);
d_lambda = fi(d_lambda_1, 0, 10, 10, fm);
theta_init = fi(theta_init_1, 1, 7, 0, fm);

if nargin < 1 || isempty(X)
    %F2F: No information found for converting the following block of code
    %F2F: Start block
    error('Input X (N x num_samples) must be provided by the testbench');
    %F2F: End block
end

% Dimensions
[fmo_1, fmo_2] = size(X);
N_fromX = fi(fmo_1, 0, 3, 0, fm);
num_samples = fi(fmo_2, 0, 6, 0, fm);
if nargin < 2 || isempty(N), 
%F2F: No information found for converting the following block of code
%F2F: Start block
N = fi(N_fromX, 0, 3, 0, fm);
%F2F: End block
 end
if N ~= N_fromX
    %F2F: No information found for converting the following block of code
    %F2F: Start block
    error('Provided N (%d) does not match rows of X (%d)', N, N_fromX);
    %F2F: End block
end

% Defaults
if nargin < 3 || isempty(d_lambda), 
%F2F: No information found for converting the following block of code
%F2F: Start block
d_lambda = fi(0.5, 0, 10, 10, fm);
%F2F: End block
 end
if nargin < 4 || isempty(cordic_iters), 
%F2F: No information found for converting the following block of code
%F2F: Start block
cordic_iters = fi(10, 0, 4, 0, fm);
%F2F: End block
 end
if nargin < 5 || isempty(theta_init), 
%F2F: No information found for converting the following block of code
%F2F: Start block
theta_init = fi(15, 1, 7, 0, fm);
%F2F: End block
 end
if nargin < 6 || isempty(K_track), 
%F2F: No information found for converting the following block of code
%F2F: Start block
K_track = fi(2^(-4) * (180/pi), 0, 10, 8, fm);
%F2F: End block
 end

theta_track = fi(zeros(1, fi_toint(num_samples)), 1, 8, 0, fm);
theta_track(1) = fi(theta_init, 1, 8, 0, fm);

for n = fi(1, 0, 1, 0, fm):num_samples-fi(1, 0, 1, 0, fm)
    % Use the pre-generated received sample for this time index
    X_sample = fi(X(:, n), 1, 10, 6, fm);

    % Beam steering (CORDIC rotation mode)
    X_steered = fi(zeros(fi_toint(N), 1) + 1j*zeros(fi_toint(N), 1), 1, 10, 6, fm);
    for k = fi(1, 0, 1, 0, fm):N
        phi_target = fi(fi(fi(2 * pi, 0, 10, 7, fm) * d_lambda * (k-fi(1, 0, 1, 0, fm)), 'SumMode', 'KeepLSB') * fi(sind_lut_s2(theta_track(n)), 'SumMode', 'KeepLSB'), 1, 10, 5, fm);
        q_in = fi(real(X_sample(k)), 1, 10, 6, fm);
        i_in = fi(imag(X_sample(k)), 1, 10, 6, fm);
        [fmo_3, fmo_4, ~] = cordic_s1(fi(q_in, 1, 10, 3, fm), fi(i_in, 1, 10, 3, fm), phi_target, cordic_iters, fi(0, 0, 1, 0, fm));
        Q_rot = fi(fmo_3, 1, 10, 6, fm);
        I_rot = fi(fmo_4, 1, 10, 6, fm);
        X_steered(k) = Q_rot + fi(1j, 0, 1, 0, fm) * I_rot;
    end

    % Sub-array grouping (Left and Right halves)
    if N < fi(4, 0, 3, 0, fm)
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        error('monopulse_tracking requires N >= 4 for 2x2 subarray grouping');
        %F2F: End block
    end
    L = fi(X_steered(1) + X_steered(2), 1, 10, 6, fm);
    R = fi(X_steered(3) + X_steered(4), 1, 10, 6, fm);

    % Phase extraction (CORDIC vectoring mode)
    [~, ~, fmo_5] = cordic_s2(fi(real(L), 1, 10, 3, fm), imag(L), fi(fi(0, 0, 1, 0, fm), 1, 10, 5, fm), cordic_iters, fi(1, 0, 1, 0, fm));
    phi_L = fi(fmo_5, 0, 10, 8, fm);
    [~, ~, fmo_6] = cordic_s2(fi(real(R), 1, 10, 3, fm), imag(R), fi(fi(0, 0, 1, 0, fm), 1, 10, 5, fm), cordic_iters, fi(1, 0, 1, 0, fm));
    phi_R = fi(fmo_6, 1, 10, 7, fm);
    % phase_diff = wrapToPi(phi_L - phi_R);
    % Fixed-point friendly phase wrapping to [-pi, pi]
    phase_diff = fi(phi_L - phi_R, 1, 10, 7, fm);
    phase_diff(:) = phase_diff - fi(2*pi, 0, 10, 7, fm)*floor((phase_diff + fi(pi, 0, 10, 8, fm))*fi(1/(2*pi), 0, 10, 1000, fm));

    % Magnitude approximation and thresholding
    mag_L = fi(abs(real(L)) + abs(imag(L)), 0, 10, 6, fm);
    mag_R = fi(abs(real(R)) + abs(imag(R)), 0, 10, 6, fm);

    if (mag_L + mag_R) > fi(0.5, 0, 10, 10, fm)
        theta_track_tmp = fi(theta_track(n) + K_track * phase_diff, 1, 10, 2, fm);
        theta_track(n+fi(1, 0, 1, 0, fm)) = fi(round(theta_track_tmp), 1, 8, 0, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        theta_track(n+fi(1, 0, 1, 0, fm)) = fi(theta_track(n), 1, 8, 0, fm);
        %F2F: End block
    end
end

end

function value = sind_lut_s2(theta)
    % Lookup table for sine values from -60 to 60 degrees with a step of 2 degrees
    % lut = [-0.8660, -0.8480, -0.8290, -0.8090, -0.7880, -0.7660, -0.7431, -0.7193, -0.6947, -0.6691, -0.6428, -0.6157, -0.5878, -0.5592, -0.5299, -0.5000, -0.4695, -0.4384, -0.4067, -0.3746, -0.3420, -0.3090, -0.2756, -0.2419, -0.2079, -0.1736, -0.1392, -0.1045, -0.0698, -0.0349, 0, 0.0349, 0.0698,0.1045, 0.1392, 0.1736, 0.2079, 0.2419, 0.2756, 0.3090, 0.3420, 0.3746, 0.4067, 0.4384,0.4695, 0.5000, 0.5299, 0.5592, 0.5878, 0.6157, 0.6428, 0.6691, 0.6947, 0.7193, 0.7431, 0.7660, 0.7880, 0.8090, 0.8290, 0.8480, 0.8660];
    fm = get_fimath();

    lut = fi([-0.8660, -0.8572, -0.8480, -0.8387, -0.8290, -0.8192, -0.8090, -0.7986, -0.7880, -0.7771, -0.7660, -0.7547, -0.7431, -0.7314, -0.7193, -0.7071, -0.6947, -0.6820, -0.6691, -0.6561, -0.6428, -0.6293, -0.6157, -0.6018, -0.5878, -0.5736, -0.5592, -0.5446, -0.5299, -0.5150, -0.5000, -0.4848, -0.4695, -0.4540, -0.4384, -0.4226, -0.4067, -0.3907, -0.3746, -0.3584, -0.3420, -0.3256, -0.3090, -0.2924, -0.2756, -0.2588, -0.2419, -0.2250, -0.2079, -0.1908, -0.1736, -0.1564, -0.1392, -0.1219, -0.1045, -0.0872, -0.0698, -0.0523, -0.0349, -0.0175, 0.0000, 0.0175, 0.0349, 0.0523, 0.0698, 0.0872, 0.1045, 0.1219, 0.1392, 0.1564, 0.1736, 0.1908, 0.2079, 0.2250, 0.2419, 0.2588, 0.2756, 0.2924, 0.3090, 0.3256, 0.3420, 0.3584, 0.3746, 0.3907, 0.4067, 0.4226, 0.4384, 0.4540, 0.4695, 0.4848, 0.5000, 0.5150, 0.5299, 0.5446, 0.5592, 0.5736, 0.5878, 0.6018, 0.6157, 0.6293, 0.6428, 0.6561, 0.6691, 0.6820, 0.6947, 0.7071, 0.7193, 0.7314, 0.7431, 0.7547, 0.7660, 0.7771, 0.7880, 0.7986, 0.8090, 0.8192, 0.8290, 0.8387, 0.8480, 0.8572, 0.8660], 1, 10, 9, fm);

    % Define the range of angles in the lookup table
    angles = fi(-60:1:60, 1, 7, 0, fm);

    % Find the index of the input angle in the lookup table
    index = fi(find(angles == theta, 1), 0, 7, 0, fm);

    % Return the corresponding value or 0 if the angle is not in the table
    if ~isempty(index)
        value = fi(lut(index), 1, 10, 9, fm);
    else
        value = fi(0, 1, 10, 9, fm);
    end
end

function [out_x, out_y, out_z] = cordic_s2(x_in, y_in, z_in, num_iterations, mode)
    % Unified CORDIC algorithm for both Rotation and Vectoring modes
    % Inputs:
    %   x_in, y_in : Input vector coordinates (Real and Imaginary)
    %   z_in       : Target angle (Rotation) or Initial angle offset (Vectoring)
    %   num_iterations : Number of iterations for the CORDIC algorithm (accuracy vs. complexity)
    %   mode       : 0: rotation mode or 1: vector mode
    % Outputs:
    %   out_x, out_y : Output vector coordinates (Real and Imaginary)


    % Precompute arctan values for the iterations
    % atan_table = atan(2.^-(0:num_iterations-1));
    fm = get_fimath();

    atan_table = fi([0.7854  0.4636  0.2450  0.1244  0.0624  0.0312  0.0156  0.0078  0.0039  0.0020  0.0018  0.0005 ], 0, 12, 12, fm);

    x_reg = fi(x_in, 1, 12, 3, fm);
    y_reg = fi(y_in, 1, 12, 3, fm);
    z_reg = fi(z_in, 1, 12, 7, fm);
    
    %% --- ROTATION MODE (Steering the Antenna Phase) ---
    if mode == fi(0, 0, 1, 0, fm)
        % 1. Quadrant Mapping: Fold the angle into [-pi/2, pi/2]
        z_reg(:) = fi_signed(mod(z_reg + fi(pi, 0, 10, 8, fm), fi(2*pi, 0, 10, 7, fm))) - fi(pi, 0, 10, 8, fm); % Wrap to [-pi, pi]
        if z_reg > fi(pi/2, 0, 10, 9, fm)
            x_reg(:) = fi_uminus(x_in); y_reg(:) = fi_uminus(y_in); z_reg(:) = z_reg - fi(pi, 0, 10, 8, fm);
        elseif z_reg < fi(-pi/2, 1, 10, 8, fm)
            x_reg(:) = fi_uminus(x_in); y_reg(:) = fi_uminus(y_in); z_reg(:) = z_reg + fi(pi, 0, 10, 8, fm);
        end
        
        % 2. Iterative Rotation
        for i = fi(0, 0, 1, 0, fm):fi_signed(num_iterations)-fi(1, 0, 1, 0, fm)
            if z_reg > fi(0, 0, 1, 0, fm)
                % Rotate counter-clockwise
                x_temp = fi(x_reg - bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg - (y_reg * 2^(-i))
                y_temp = fi(y_reg + bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg + (
                z_temp = fi(z_reg - atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            else
                % Rotate clockwise
                x_temp = fi(x_reg + bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg + (y_reg * 2^(-i))
                y_temp = fi(y_reg - bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg - (x_reg * 2^(-i))
                z_temp = fi(z_reg + atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            end
            x_reg(:) = x_temp; y_reg(:) = y_temp; z_reg(:) = z_temp;
        end
        
    %% --- VECTORING MODE (Extracting the Phase) ---
    elseif mode == fi(1, 0, 1, 0, fm)
        % 1. Quadrant Mapping: Force the vector into the right half-plane (X > 0)
        if x_reg < fi(0, 0, 1, 0, fm)
            if y_reg >= fi(0, 0, 1, 0, fm)
                z_reg(:) = z_reg + fi(pi, 0, 10, 8, fm); % Vector was in Q2
            else
                z_reg(:) = z_reg - fi(pi, 0, 10, 8, fm); % Vector was in Q3
            end
            x_reg(:) = fi_uminus(x_reg); 
            y_reg(:) = fi_uminus(y_reg);
        end
        
        % 2. Iterative Vectoring (Drive Y to 0)
        for i = fi(0, 0, 1, 0, fm):fi_signed(num_iterations)-fi(1, 0, 1, 0, fm)
            if y_reg > fi(0, 0, 1, 0, fm)
                % Rotate clockwise to reduce Y
                x_temp = fi(x_reg + bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg + (y_reg * 2^(-i))
                y_temp = fi(y_reg - bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg - (x_reg * 2^(-i))
                z_temp = fi(z_reg + atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            else
                % Rotate counter-clockwise to increase Y
                x_temp = fi(x_reg - bitsra(y_reg, fi_toint(i)), 1, 12, 3, fm); % x_reg - (y_reg * 2^(-i))
                y_temp = fi(y_reg + bitsra(x_reg, fi_toint(i)), 1, 12, 3, fm); % y_reg + (x_reg * 2^(-i))
                z_temp = fi(z_reg - atan_table(i+fi(1, 0, 1, 0, fm)), 1, 12, 9, fm);
            end
            x_reg(:) = x_temp; y_reg(:) = y_temp; z_reg(:) = z_temp;
        end
    end
    
    % --- Apply CORDIC Gain (approx 1.6467 for 10 iters) ---
    % In a strict 3000 FF hardware design, you might skip this division 
    % if you only care about the phase (z_reg) or relative magnitude.
    % gain = prod(sqrt(1 + 2.^-(2*(0:num_iterations-1))));
    gain = fi(1.6467, 0, 10, 9, fm); % Precomputed gain for 10 iterations
    out_x = fi(fi_div(x_reg, gain), 1, 10, 2, fm);
    out_y = fi(fi_div(y_reg, gain), 1, 10, 2, fm);
    out_z = fi(z_reg, 1, 10, 7, fm);
end



function ntype = divideType(a,b)
    coder.inline( 'always' );
    nt1 = numerictype( a );
    nt2 = numerictype( b );
    maxFL = max( [ min( nt1.WordLength, nt1.FractionLength ), min( nt2.WordLength, nt2.FractionLength ) ] );
    FL = max( maxFL, 24 );
    extraBits = (FL - maxFL);
    WL = nt1.WordLength + nt2.WordLength;
    WL = min( WL, 124 );
    if (WL + extraBits)<64
        ntype = numerictype( nt1.Signed || nt2.Signed, WL + extraBits, FL );
    else
        ntype = numerictype( nt1.Signed || nt2.Signed, WL, FL );
    end
end


function c = fi_div(a,b)
    coder.inline( 'always' );
    a1 = fi( a, 'RoundMode', 'fix' );
    b1 = fi( b, 'RoundMode', 'fix' );
    nType = divideType( a1, b1 );
    if isfi( a ) && isfi( b ) && isscalar( b )
        c1 = divide( nType, a1, b1 );
        c = fi( c1, numerictype( c1 ), fimath( a ) );
    else
        c = fi( a / b, nType );
    end
end


function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end


function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end


function y = fi_uminus(a)
    coder.inline( 'always' );
    if isfi( a )
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = -fi( a, new_nt, fimath( a ) );
    else
        y = -a;
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Saturate',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
