%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [E, error, W_history] = search_lms_cordic_fixpt(x1_q, x1_i, x2_q, x2_i, x3_q, x3_i, x4_q, x4_i, mu, num_iterations, N, step)

    %% 1. System & Environment Parameters Setup
    % --- Search Parameters ---
    fm = get_fimath();

    scan_start = fi(-60, 1, 7, 0, fm);       % Start angle of scan
    scan_end = fi(60, 0, 6, 0, fm);          % End angle of scan
    scan_step = fi(step, 0, 2, 0, fm);          % Scan resolution (step size in degrees)
    scan_angles = fi(scan_start:scan_step:scan_end, 1, 7, 0, fm);
    num_scan_points = fi(length(scan_angles), 0, 6, 0, fm);

    %% 2. Signal Setup
    X = fi([fi(x1_q + fi(1j, 0, 1, 0, fm)*x1_i, 1, 10, 2, fm); x2_q + fi(1j, 0, 1, 0, fm)*x2_i; x3_q + fi(1j, 0, 1, 0, fm)*x3_i; x4_q + fi(1j, 0, 1, 0, fm)*x4_i], 1, 10, 2, fm);

    %% 2. Hardware Algo: Sequential Scanning & Energy Estimation
    % Initialize array to store calculated energy for each scanned angle

    scan_energy = fi(zeros(1, fi_toint(num_scan_points)), 0, 10, 5, fm);

    % Sweep through all angles
    for i = fi(1, 0, 1, 0, fm):num_scan_points
        current_angle = fi(scan_angles(i), 1, 7, 0, fm);

        SUM_Q = fi(0, 1, 10, 4, fm);
        SUM_I = fi(0, 1, 10, 5, fm);

        for k = fi(1, 0, 1, 0, fm):N
            % Calculate phase: phi = 2*pi * d/L * (k-1) * sin(theta)
            % phi = 2 * pi * 0.5 * (k-1) * sind(current_angle);
            phi = fi(fi(fi(2 * pi * 0.5, 0, 10, 8, fm) * (k-fi(1, 0, 1, 0, fm)), 'SumMode', 'KeepLSB') * fi(sind_lut(current_angle), 'SumMode', 'KeepLSB'), 1, 10, 5, fm);

            % CORDIC Rotation (Implemented as a function for clarity)
            [fmo_1, fmo_2] = cordic(real(X(k, i)), imag(X(k, i)), phi, fi(12, 0, 4, 0, fm));
            Q_rot = fi(fmo_1, 1, 10, 5, fm);
            I_rot = fi(fmo_2, 1, 10, 5, fm);

            SUM_I(:) = SUM_I + I_rot;
            SUM_Q(:) = SUM_Q + Q_rot;
        end

        % Energy Estimation (Accumulate energy over the sample window)
        energy_approx = fi(sum(abs(SUM_I) + abs(SUM_Q)), 0, 10, 5, fm); 

        % Store the energy for this angle
        scan_energy(i) = fi(energy_approx, 0, 10, 5, fm);
    end

    %% 3. Peak Detection
    % Find the maximum energy and its corresponding angle
    E = fi(scan_energy, 0, 10, 5, fm);

    %% 4. LMS Initialization
    W = fi([1+0j; 0+0j; 0+0j; 0+0j], 1, 10, 8, fm);       % Power Inversion constraint: W1=1
    W_history = fi(zeros(fi_toint(N), fi_toint(num_iterations)) + 1j*zeros(fi_toint(N), fi_toint(num_iterations)), 1, 10, 8, fm);
    error_power = fi(zeros(1, fi_toint(num_iterations)), 0, 16, 2, fm); % To store the "Error Function
    
    % csign = @(x) (sign(real(x)+(real(x)==0)) + 1j * sign(imag(x)+(imag(x)==0)));
    % csign_sep = @(q, i) (sign(q+(q==0)) + 1j * sign(i+(i==0)));

    %% 5. LMS Main Loop
    for n = fi(1, 0, 1, 0, fm):num_iterations
        % --- Apply Weights ---
        y = fi(W' * X(:, n+num_scan_points), 1, 10, 3, fm); 

        % Record Squared Error (Output Power) for the Learning Curve
        error_power(n) = fi(abs(y)^2, 0, 16, 2, fm);

        % --- Sign-LMS Update ---
        error_lms = fi(y, 1, 10, 3, fm);
        for k = fi(1, 0, 1, 0, fm):N-fi(1, 0, 1, 0, fm)
            Z = fi(fi_signed(X(k+fi(1, 0, 1, 0, fm), n+num_scan_points)) - X(k, n+num_scan_points), 1, 10, 3, fm);   % Use Target Blocking Matrix to block the target signal and prevent the elimination of target signal
            W(k+fi(1, 0, 1, 0, fm)) = fi_signed(W(k+fi(1, 0, 1, 0, fm))) - mu * conj(csign(error_lms)) * csign(Z);
        end

        W_history(:, n) = fi(W, 1, 10, 8, fm);
    end
    error = fi(error_power, 0, 16, 2, fm);
end

function value = sind_lut(theta)
    % Lookup table for sine values from -60 to 60 degrees with a step of 2 degrees
    fm = get_fimath();

    lut = fi([-0.8660, -0.8480, -0.8290, -0.8090, -0.7880, -0.7660, -0.7431, -0.7193, -0.6947, -0.6691, -0.6428, -0.6157, -0.5878, -0.5592, -0.5299, -0.5000, -0.4695, -0.4384, -0.4067, -0.3746, -0.3420, -0.3090, -0.2756, -0.2419, -0.2079, -0.1736, -0.1392, -0.1045, -0.0698, -0.0349, 0, 0.0349, 0.0698,0.1045, 0.1392, 0.1736, 0.2079, 0.2419, 0.2756, 0.3090, 0.3420, 0.3746, 0.4067, 0.4384,0.4695, 0.5000, 0.5299, 0.5592, 0.5878, 0.6157, 0.6428, 0.6691, 0.6947, 0.7193, 0.7431, 0.7660, 0.7880, 0.8090, 0.8290, 0.8480, 0.8660], 1, 10, 9, fm);

    % Define the range of angles in the lookup table
    angles = fi(-60:2:60, 1, 7, 0, fm);

    % Find the index of the input angle in the lookup table
    index = fi(find(angles == theta, 1), 0, 6, 0, fm);

    % Return the corresponding value or 0 if the angle is not in the table
    if ~isempty(index)
        value = fi(lut(index), 1, 10, 9, fm);
    else
        %F2F: No information found for converting the following block of code
        %F2F: Start block
        value = fi(0, 1, 10, 9, fm);
        %F2F: End block
    end
end

function [z_q, z_i] = cordic(x_q, x_i, y, num_iterations)
    % CORDIC Rotation Mode for Phase Compensation
    % Input: x_q, x_i (real and imaginary parts of input), y (rotation angle in radians), num_iterations (number of CORDIC iterations)
    % Output: z_q, z_i (real and imaginary parts of rotated output)

    % Precompute arctan values for the iterations
    % atan_table = atan(2.^-(0:num_iterations-1));
    fm = get_fimath();

    atan_table = fi([0.7854  0.4636  0.2450  0.1244  0.0624  0.0312  0.0156  0.0078  0.0039  0.0020  0.0018  0.0005 ], 0, 10, 10, fm);

    % Initialize CORDIC registers
    x_reg = fi(x_q, 1, 10, 5, fm);
    y_reg = fi(x_i, 1, 10, 5, fm);
    z_reg = fi(y, 1, 10, 5, fm);

    for i = fi(0, 0, 1, 0, fm):fi_signed(num_iterations)-fi(1, 0, 1, 0, fm)
        if z_reg > fi(0, 0, 1, 0, fm)
            x_temp = fi(x_reg - (y_reg * fi(fi(fi(2, 0, 2, 0, fm), 'ProductMode', 'SpecifyPrecision', 'ProductWordLength', 10, 'ProductFractionLength', 9, 'Signedness', 'Unsigned', 'WordLength', 10, 'FractionLength', 9)^(fi_uminus(i)), fm)), 1, 10, 5, fm);
            y_temp = fi(y_reg + (x_reg * fi(fi(fi(2, 0, 2, 0, fm), 'ProductMode', 'SpecifyPrecision', 'ProductWordLength', 10, 'ProductFractionLength', 9, 'Signedness', 'Unsigned', 'WordLength', 10, 'FractionLength', 9)^(fi_uminus(i)), fm)), 1, 10, 5, fm);
            z_temp = fi(z_reg - atan_table(i+fi(1, 0, 1, 0, fm)), 1, 10, 6, fm);
        else
            x_temp = fi(x_reg + (y_reg * fi(fi(fi(2, 0, 2, 0, fm), 'ProductMode', 'SpecifyPrecision', 'ProductWordLength', 10, 'ProductFractionLength', 9, 'Signedness', 'Unsigned', 'WordLength', 10, 'FractionLength', 9)^(fi_uminus(i)), fm)), 1, 10, 5, fm);
            y_temp = fi(y_reg - (x_reg * fi(fi(fi(2, 0, 2, 0, fm), 'ProductMode', 'SpecifyPrecision', 'ProductWordLength', 10, 'ProductFractionLength', 9, 'Signedness', 'Unsigned', 'WordLength', 10, 'FractionLength', 9)^(fi_uminus(i)), fm)), 1, 10, 5, fm);
            z_temp = fi(z_reg + atan_table(i+fi(1, 0, 1, 0, fm)), 1, 10, 6, fm);
        end
        x_reg(:) = x_temp;
        y_reg(:) = y_temp;
        z_reg = fi(z_temp, 1, 10, 5, fm);
    end

    % Output the rotated coordinates
    z_q = fi(x_reg*fi(1/1.64, 0, 10, 10, fm), 1, 10, 5, fm);
    z_i = fi(y_reg*fi(1/1.64, 0, 10, 10, fm), 1, 10, 5, fm);
end

function result = csign(x)
    % Custom complex sign function that treats zero as positive
    fm = get_fimath();

    result = fi(sign(real(x) + (real(x) == fi(0, 0, 1, 0, fm))) + fi(1j, 0, 1, 0, fm) * sign(imag(x) + (imag(x) == fi(0, 0, 1, 0, fm))), 1, 2, 0, fm);
end



function y = fi_signed(a)
    coder.inline( 'always' );
    if isfi( a ) && ~(issigned( a ))
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = fi( a, new_nt, fimath( a ) );
    else
        y = a;
    end
end


function y = fi_toint(u)
    coder.inline( 'always' );
    if isfi( u )
        nt = numerictype( u );
        s = nt.SignednessBool;
        wl = nt.WordLength;
        y = int32( fi( u, s, wl, 0, hdlfimath ) );
    else
        y = int32( u );
    end
end


function y = fi_uminus(a)
    coder.inline( 'always' );
    if isfi( a )
        nt = numerictype( a );
        new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
        y = -fi( a, new_nt, fimath( a ) );
    else
        y = -a;
    end
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Saturate',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
