%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [E,error,W_history] = search_lms_cordic_wrapper_fixpt(x1_q,x1_i,x2_q,x2_i,x3_q,x3_i,x4_q,x4_i,mu,num_iterations,N,step)
    fm = get_fimath();
    x1_q_in = fi( x1_q, 1, 10, 2, fm );
    x1_i_in = fi( x1_i, 1, 10, 2, fm );
    x2_q_in = fi( x2_q, 1, 10, 2, fm );
    x2_i_in = fi( x2_i, 1, 10, 2, fm );
    x3_q_in = fi( x3_q, 1, 10, 2, fm );
    x3_i_in = fi( x3_i, 1, 10, 2, fm );
    x4_q_in = fi( x4_q, 1, 10, 2, fm );
    x4_i_in = fi( x4_i, 1, 10, 2, fm );
    mu_in = fi( mu, 0, 10, 15, fm );
    num_iterations_in = fi( num_iterations, 0, 6, 0, fm );
    N_in = fi( N, 0, 3, 0, fm );
    step_in = fi( step, 0, 2, 0, fm );
    [E_out,error_out,W_history_out] = search_lms_cordic_fixpt( x1_q_in, x1_i_in, x2_q_in, x2_i_in, x3_q_in, x3_i_in, x4_q_in, x4_i_in, mu_in, num_iterations_in, N_in, step_in );
    E = double( E_out );
    error = double( error_out );
    W_history = double( W_history_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Saturate',...
	     'ProductMode','FullPrecision',...
	     'SumMode','FullPrecision');
end
